export const IPC_CHANNELS = {
  APP_GET_VERSION: 'app:get-version',
  DB_GET_META: 'db:get-meta',
  DB_SET_META: 'db:set-meta',
  DB_GET_PATH: 'db:get-path',
  LIBRARY_SCAN: 'library:scan',
  LIBRARY_GET_GAMES: 'library:get-games',
  LIBRARY_REMOVE_GAME: 'library:remove-game',
  ARTWORK_FETCH_LIBRARY: 'artwork:fetch-library',
  GAME_GET_DETAIL: 'game:get-detail',
  GAME_TOGGLE_FAVORITE: 'game:toggle-favorite',
  GAME_OPEN_INSTALL_FOLDER: 'game:open-install-folder',
  GAME_LAUNCH: 'game:launch',
  GAME_SESSION_UPDATE: 'game:session-update',
  COVER_GET_OPTIONS: 'cover:get-options',
  COVER_SET_FROM_URL: 'cover:set-from-url',
  COVER_SET_FROM_FILE: 'cover:set-from-file',
  HERO_GET_OPTIONS: 'hero:get-options',
  HERO_SET_FROM_URL: 'hero:set-from-url',
  HERO_SET_FROM_FILE: 'hero:set-from-file',
  GAME_UPDATE_NOTES: 'game:update-notes',
  GAME_TRANSLATE_DESCRIPTION: 'game:translate-description',
  SHELL_OPEN_EXTERNAL: 'shell:open-external',
  UPDATE_CHECK: 'update:check-for-updates',
  UPDATE_START_DOWNLOAD: 'update:start-download-update',
  UPDATE_INSTALL: 'update:install-update',
  UPDATE_EVENT: 'update:event'
} as const
